// Mocks generated by Mockito 5.4.6 from annotations
// in forecast_app_pet_proj/test/data/repositories_data_impl/data_remote_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:dio/dio.dart' as _i3;
import 'package:forecast_app_pet_proj/core/network/dio_client.dart' as _i8;
import 'package:forecast_app_pet_proj/core/network/remote_params.dart' as _i9;
import 'package:forecast_app_pet_proj/core/services/geo/geo_location_service.dart'
    as _i6;
import 'package:forecast_app_pet_proj/domain/entities/meteo_enity/current_weather.dart'
    as _i5;
import 'package:forecast_app_pet_proj/domain/entities/meteo_enity/daily_weather.dart'
    as _i14;
import 'package:forecast_app_pet_proj/domain/entities/meteo_enity/hourly_weather.dart'
    as _i13;
import 'package:forecast_app_pet_proj/domain/entities/meteo_enity/location_info.dart'
    as _i4;
import 'package:forecast_app_pet_proj/domain/entities/meteo_enity/meteo_enity.dart'
    as _i11;
import 'package:geolocator/geolocator.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:shared_preferences/src/shared_preferences_legacy.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePosition_0 extends _i1.SmartFake implements _i2.Position {
  _FakePosition_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_1 extends _i1.SmartFake implements _i3.Dio {
  _FakeDio_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_2 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocationInfo_3 extends _i1.SmartFake implements _i4.LocationInfo {
  _FakeLocationInfo_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCurrentWeather_4 extends _i1.SmartFake
    implements _i5.CurrentWeather {
  _FakeCurrentWeather_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GeoLocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeoLocationService extends _i1.Mock
    implements _i6.GeoLocationService {
  MockGeoLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<bool> isLocationServiceEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isLocationServiceEnabled, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<_i2.LocationPermission> checkPermission() =>
      (super.noSuchMethod(
            Invocation.method(#checkPermission, []),
            returnValue: _i7.Future<_i2.LocationPermission>.value(
              _i2.LocationPermission.denied,
            ),
          )
          as _i7.Future<_i2.LocationPermission>);

  @override
  _i7.Future<_i2.LocationPermission> requestPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, []),
            returnValue: _i7.Future<_i2.LocationPermission>.value(
              _i2.LocationPermission.denied,
            ),
          )
          as _i7.Future<_i2.LocationPermission>);

  @override
  _i7.Future<_i2.Position> getCurrentPosition() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPosition, []),
            returnValue: _i7.Future<_i2.Position>.value(
              _FakePosition_0(this, Invocation.method(#getCurrentPosition, [])),
            ),
          )
          as _i7.Future<_i2.Position>);

  @override
  _i7.Future<bool> isGeoAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isGeoAvailable, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<_i2.Position> getPositionSafely() =>
      (super.noSuchMethod(
            Invocation.method(#getPositionSafely, []),
            returnValue: _i7.Future<_i2.Position>.value(
              _FakePosition_0(this, Invocation.method(#getPositionSafely, [])),
            ),
          )
          as _i7.Future<_i2.Position>);
}

/// A class which mocks [DioClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioClient extends _i1.Mock implements _i8.DioClient {
  MockDioClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Dio get dioClient =>
      (super.noSuchMethod(
            Invocation.getter(#dioClient),
            returnValue: _FakeDio_1(this, Invocation.getter(#dioClient)),
          )
          as _i3.Dio);

  @override
  _i7.Future<Map<String, dynamic>?> getForecastRowData({
    required _i9.Params? param,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getForecastRowData, [], {#param: param}),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i10.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key]))
          as List<String>?);

  @override
  _i7.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [Position].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockPosition extends _i1.Mock implements _i2.Position {
  MockPosition() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double get latitude =>
      (super.noSuchMethod(Invocation.getter(#latitude), returnValue: 0.0)
          as double);

  @override
  double get longitude =>
      (super.noSuchMethod(Invocation.getter(#longitude), returnValue: 0.0)
          as double);

  @override
  DateTime get timestamp =>
      (super.noSuchMethod(
            Invocation.getter(#timestamp),
            returnValue: _FakeDateTime_2(this, Invocation.getter(#timestamp)),
          )
          as DateTime);

  @override
  double get altitude =>
      (super.noSuchMethod(Invocation.getter(#altitude), returnValue: 0.0)
          as double);

  @override
  double get altitudeAccuracy =>
      (super.noSuchMethod(
            Invocation.getter(#altitudeAccuracy),
            returnValue: 0.0,
          )
          as double);

  @override
  double get accuracy =>
      (super.noSuchMethod(Invocation.getter(#accuracy), returnValue: 0.0)
          as double);

  @override
  double get heading =>
      (super.noSuchMethod(Invocation.getter(#heading), returnValue: 0.0)
          as double);

  @override
  double get headingAccuracy =>
      (super.noSuchMethod(Invocation.getter(#headingAccuracy), returnValue: 0.0)
          as double);

  @override
  double get speed =>
      (super.noSuchMethod(Invocation.getter(#speed), returnValue: 0.0)
          as double);

  @override
  double get speedAccuracy =>
      (super.noSuchMethod(Invocation.getter(#speedAccuracy), returnValue: 0.0)
          as double);

  @override
  bool get isMocked =>
      (super.noSuchMethod(Invocation.getter(#isMocked), returnValue: false)
          as bool);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [MeteoEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeteoEntity extends _i1.Mock implements _i11.MeteoEntity {
  MockMeteoEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get cityName =>
      (super.noSuchMethod(
            Invocation.getter(#cityName),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#cityName),
            ),
          )
          as String);

  @override
  _i4.LocationInfo get location =>
      (super.noSuchMethod(
            Invocation.getter(#location),
            returnValue: _FakeLocationInfo_3(
              this,
              Invocation.getter(#location),
            ),
          )
          as _i4.LocationInfo);

  @override
  _i5.CurrentWeather get current =>
      (super.noSuchMethod(
            Invocation.getter(#current),
            returnValue: _FakeCurrentWeather_4(
              this,
              Invocation.getter(#current),
            ),
          )
          as _i5.CurrentWeather);

  @override
  List<_i13.HourlyWeather> get hourlyForecast =>
      (super.noSuchMethod(
            Invocation.getter(#hourlyForecast),
            returnValue: <_i13.HourlyWeather>[],
          )
          as List<_i13.HourlyWeather>);

  @override
  List<_i14.DailyWeather> get dailyForecast =>
      (super.noSuchMethod(
            Invocation.getter(#dailyForecast),
            returnValue: <_i14.DailyWeather>[],
          )
          as List<_i14.DailyWeather>);
}
