// Mocks generated by Mockito 5.4.6 from annotations
// in forecast_app_pet_proj/test/presentation/state_management/cubit/bottom_card_change_cubit/bottom_card_change_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i2;
import 'package:forecast_app_pet_proj/data/repositories_data_impl/data_local_repo.dart'
    as _i5;
import 'package:forecast_app_pet_proj/domain/entities/meteo_enity/current_weather.dart'
    as _i4;
import 'package:forecast_app_pet_proj/domain/entities/meteo_enity/daily_weather.dart'
    as _i9;
import 'package:forecast_app_pet_proj/domain/entities/meteo_enity/hourly_weather.dart'
    as _i11;
import 'package:forecast_app_pet_proj/domain/entities/meteo_enity/location_info.dart'
    as _i3;
import 'package:forecast_app_pet_proj/domain/entities/meteo_enity/meteo_enity.dart'
    as _i8;
import 'package:forecast_app_pet_proj/domain/failures/failure_interface.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_1 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocationInfo_2 extends _i1.SmartFake implements _i3.LocationInfo {
  _FakeLocationInfo_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCurrentWeather_3 extends _i1.SmartFake
    implements _i4.CurrentWeather {
  _FakeCurrentWeather_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DataLocalRepoIMPL].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataLocalRepoIMPL extends _i1.Mock implements _i5.DataLocalRepoIMPL {
  MockDataLocalRepoIMPL() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i8.MeteoEntity>> getFromCache({
    required String? stringKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFromCache, [], {#stringKey: stringKey}),
            returnValue:
                _i6.Future<_i2.Either<_i7.Failure, _i8.MeteoEntity>>.value(
                  _FakeEither_0<_i7.Failure, _i8.MeteoEntity>(
                    this,
                    Invocation.method(#getFromCache, [], {
                      #stringKey: stringKey,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.Failure, _i8.MeteoEntity>>);

  @override
  _i6.Future<void> cleanCache() =>
      (super.noSuchMethod(
            Invocation.method(#cleanCache, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [DailyWeather].
///
/// See the documentation for Mockito's code generation for more information.
class MockDailyWeather extends _i1.Mock implements _i9.DailyWeather {
  MockDailyWeather() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get date =>
      (super.noSuchMethod(
            Invocation.getter(#date),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#date),
            ),
          )
          as String);

  @override
  DateTime get rowDate =>
      (super.noSuchMethod(
            Invocation.getter(#rowDate),
            returnValue: _FakeDateTime_1(this, Invocation.getter(#rowDate)),
          )
          as DateTime);

  @override
  double get tempMax =>
      (super.noSuchMethod(Invocation.getter(#tempMax), returnValue: 0.0)
          as double);

  @override
  double get tempMin =>
      (super.noSuchMethod(Invocation.getter(#tempMin), returnValue: 0.0)
          as double);

  @override
  DateTime get sunrise =>
      (super.noSuchMethod(
            Invocation.getter(#sunrise),
            returnValue: _FakeDateTime_1(this, Invocation.getter(#sunrise)),
          )
          as DateTime);

  @override
  DateTime get sunset =>
      (super.noSuchMethod(
            Invocation.getter(#sunset),
            returnValue: _FakeDateTime_1(this, Invocation.getter(#sunset)),
          )
          as DateTime);
}

/// A class which mocks [HourlyWeather].
///
/// See the documentation for Mockito's code generation for more information.
class MockHourlyWeather extends _i1.Mock implements _i11.HourlyWeather {
  MockHourlyWeather() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get validTimeFormat =>
      (super.noSuchMethod(
            Invocation.getter(#validTimeFormat),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#validTimeFormat),
            ),
          )
          as String);

  @override
  DateTime get time =>
      (super.noSuchMethod(
            Invocation.getter(#time),
            returnValue: _FakeDateTime_1(this, Invocation.getter(#time)),
          )
          as DateTime);

  @override
  double get temperature =>
      (super.noSuchMethod(Invocation.getter(#temperature), returnValue: 0.0)
          as double);

  @override
  double get precipitationProbability =>
      (super.noSuchMethod(
            Invocation.getter(#precipitationProbability),
            returnValue: 0.0,
          )
          as double);
}

/// A class which mocks [MeteoEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeteoEntity extends _i1.Mock implements _i8.MeteoEntity {
  MockMeteoEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get cityName =>
      (super.noSuchMethod(
            Invocation.getter(#cityName),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#cityName),
            ),
          )
          as String);

  @override
  _i3.LocationInfo get location =>
      (super.noSuchMethod(
            Invocation.getter(#location),
            returnValue: _FakeLocationInfo_2(
              this,
              Invocation.getter(#location),
            ),
          )
          as _i3.LocationInfo);

  @override
  _i4.CurrentWeather get current =>
      (super.noSuchMethod(
            Invocation.getter(#current),
            returnValue: _FakeCurrentWeather_3(
              this,
              Invocation.getter(#current),
            ),
          )
          as _i4.CurrentWeather);

  @override
  List<_i11.HourlyWeather> get hourlyForecast =>
      (super.noSuchMethod(
            Invocation.getter(#hourlyForecast),
            returnValue: <_i11.HourlyWeather>[],
          )
          as List<_i11.HourlyWeather>);

  @override
  List<_i9.DailyWeather> get dailyForecast =>
      (super.noSuchMethod(
            Invocation.getter(#dailyForecast),
            returnValue: <_i9.DailyWeather>[],
          )
          as List<_i9.DailyWeather>);
}
