// Mocks generated by Mockito 5.4.6 from annotations
// in forecast_app_pet_proj/test/presentation/state_management/bloc/bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:dartz/dartz.dart' as _i3;
import 'package:dio/dio.dart' as _i6;
import 'package:forecast_app_pet_proj/core/network/dio_client.dart' as _i15;
import 'package:forecast_app_pet_proj/core/network/remote_params.dart' as _i16;
import 'package:forecast_app_pet_proj/core/services/geo/geo_location_service.dart'
    as _i14;
import 'package:forecast_app_pet_proj/domain/entities/meteo_enity/current_weather.dart'
    as _i8;
import 'package:forecast_app_pet_proj/domain/entities/meteo_enity/daily_weather.dart'
    as _i20;
import 'package:forecast_app_pet_proj/domain/entities/meteo_enity/hourly_weather.dart'
    as _i19;
import 'package:forecast_app_pet_proj/domain/entities/meteo_enity/location_info.dart'
    as _i7;
import 'package:forecast_app_pet_proj/domain/entities/meteo_enity/meteo_enity.dart'
    as _i12;
import 'package:forecast_app_pet_proj/domain/failures/failure_interface.dart'
    as _i11;
import 'package:forecast_app_pet_proj/domain/repositories_interface/data_local_repo_inter.dart'
    as _i2;
import 'package:forecast_app_pet_proj/domain/repositories_interface/remote_data_repo.dart'
    as _i4;
import 'package:forecast_app_pet_proj/domain/use_cases/favorites_use_case/favorites_use_case.dart'
    as _i17;
import 'package:forecast_app_pet_proj/domain/use_cases/local_data_use_case/local_data_source_use_case.dart'
    as _i9;
import 'package:forecast_app_pet_proj/domain/use_cases/remote_data_use_cases/remote_data_use_case.dart'
    as _i13;
import 'package:geolocator/geolocator.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDataLocalRepo_0 extends _i1.SmartFake implements _i2.DataLocalRepo {
  _FakeDataLocalRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoteDataRepo_2 extends _i1.SmartFake
    implements _i4.RemoteDataRepo {
  _FakeRemoteDataRepo_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePosition_3 extends _i1.SmartFake implements _i5.Position {
  _FakePosition_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_4 extends _i1.SmartFake implements _i6.Dio {
  _FakeDio_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocationInfo_5 extends _i1.SmartFake implements _i7.LocationInfo {
  _FakeLocationInfo_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCurrentWeather_6 extends _i1.SmartFake
    implements _i8.CurrentWeather {
  _FakeCurrentWeather_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LocalDataSourceUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataSourceUseCase extends _i1.Mock
    implements _i9.LocalDataSourceUseCase {
  MockLocalDataSourceUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DataLocalRepo get aRepo =>
      (super.noSuchMethod(
            Invocation.getter(#aRepo),
            returnValue: _FakeDataLocalRepo_0(this, Invocation.getter(#aRepo)),
          )
          as _i2.DataLocalRepo);

  @override
  _i10.Future<void> cleanCache() =>
      (super.noSuchMethod(
            Invocation.method(#cleanCache, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i3.Either<_i11.Failure, _i12.MeteoEntity>> loadFromCache({
    required String? cityName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadFromCache, [], {#cityName: cityName}),
            returnValue:
                _i10.Future<_i3.Either<_i11.Failure, _i12.MeteoEntity>>.value(
                  _FakeEither_1<_i11.Failure, _i12.MeteoEntity>(
                    this,
                    Invocation.method(#loadFromCache, [], {
                      #cityName: cityName,
                    }),
                  ),
                ),
          )
          as _i10.Future<_i3.Either<_i11.Failure, _i12.MeteoEntity>>);
}

/// A class which mocks [RemoteDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataUseCase extends _i1.Mock implements _i13.RemoteDataUseCase {
  MockRemoteDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RemoteDataRepo get aRepo =>
      (super.noSuchMethod(
            Invocation.getter(#aRepo),
            returnValue: _FakeRemoteDataRepo_2(this, Invocation.getter(#aRepo)),
          )
          as _i4.RemoteDataRepo);

  @override
  _i10.Future<_i3.Either<_i11.Failure, _i12.MeteoEntity>> getByName({
    required bool? isMetric,
    required String? q,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getByName, [], {#isMetric: isMetric, #q: q}),
            returnValue:
                _i10.Future<_i3.Either<_i11.Failure, _i12.MeteoEntity>>.value(
                  _FakeEither_1<_i11.Failure, _i12.MeteoEntity>(
                    this,
                    Invocation.method(#getByName, [], {
                      #isMetric: isMetric,
                      #q: q,
                    }),
                  ),
                ),
          )
          as _i10.Future<_i3.Either<_i11.Failure, _i12.MeteoEntity>>);

  @override
  _i10.Future<_i3.Either<_i11.Failure, _i12.MeteoEntity>> getByGeo({
    required bool? isMetric,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getByGeo, [], {#isMetric: isMetric}),
            returnValue:
                _i10.Future<_i3.Either<_i11.Failure, _i12.MeteoEntity>>.value(
                  _FakeEither_1<_i11.Failure, _i12.MeteoEntity>(
                    this,
                    Invocation.method(#getByGeo, [], {#isMetric: isMetric}),
                  ),
                ),
          )
          as _i10.Future<_i3.Either<_i11.Failure, _i12.MeteoEntity>>);
}

/// A class which mocks [GeoLocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeoLocationService extends _i1.Mock
    implements _i14.GeoLocationService {
  MockGeoLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<bool> isLocationServiceEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isLocationServiceEnabled, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<_i5.LocationPermission> checkPermission() =>
      (super.noSuchMethod(
            Invocation.method(#checkPermission, []),
            returnValue: _i10.Future<_i5.LocationPermission>.value(
              _i5.LocationPermission.denied,
            ),
          )
          as _i10.Future<_i5.LocationPermission>);

  @override
  _i10.Future<_i5.LocationPermission> requestPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, []),
            returnValue: _i10.Future<_i5.LocationPermission>.value(
              _i5.LocationPermission.denied,
            ),
          )
          as _i10.Future<_i5.LocationPermission>);

  @override
  _i10.Future<_i5.Position> getCurrentPosition() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPosition, []),
            returnValue: _i10.Future<_i5.Position>.value(
              _FakePosition_3(this, Invocation.method(#getCurrentPosition, [])),
            ),
          )
          as _i10.Future<_i5.Position>);

  @override
  _i10.Future<bool> isGeoAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isGeoAvailable, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<_i5.Position> getPositionSafely() =>
      (super.noSuchMethod(
            Invocation.method(#getPositionSafely, []),
            returnValue: _i10.Future<_i5.Position>.value(
              _FakePosition_3(this, Invocation.method(#getPositionSafely, [])),
            ),
          )
          as _i10.Future<_i5.Position>);
}

/// A class which mocks [DioClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioClient extends _i1.Mock implements _i15.DioClient {
  MockDioClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Dio get dioClient =>
      (super.noSuchMethod(
            Invocation.getter(#dioClient),
            returnValue: _FakeDio_4(this, Invocation.getter(#dioClient)),
          )
          as _i6.Dio);

  @override
  _i10.Future<Map<String, dynamic>?> getForecastRowData({
    required _i16.Params? param,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getForecastRowData, [], {#param: param}),
            returnValue: _i10.Future<Map<String, dynamic>?>.value(),
          )
          as _i10.Future<Map<String, dynamic>?>);
}

/// A class which mocks [RemoteDataRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataRepo extends _i1.Mock implements _i4.RemoteDataRepo {
  MockRemoteDataRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i3.Either<_i11.Failure, _i12.MeteoEntity>> getRespByName({
    required bool? isMetric,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRespByName, [], {
              #isMetric: isMetric,
              #name: name,
            }),
            returnValue:
                _i10.Future<_i3.Either<_i11.Failure, _i12.MeteoEntity>>.value(
                  _FakeEither_1<_i11.Failure, _i12.MeteoEntity>(
                    this,
                    Invocation.method(#getRespByName, [], {
                      #isMetric: isMetric,
                      #name: name,
                    }),
                  ),
                ),
          )
          as _i10.Future<_i3.Either<_i11.Failure, _i12.MeteoEntity>>);

  @override
  _i10.Future<_i3.Either<_i11.Failure, _i12.MeteoEntity>> getRespByGeo({
    required bool? isMetric,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRespByGeo, [], {#isMetric: isMetric}),
            returnValue:
                _i10.Future<_i3.Either<_i11.Failure, _i12.MeteoEntity>>.value(
                  _FakeEither_1<_i11.Failure, _i12.MeteoEntity>(
                    this,
                    Invocation.method(#getRespByGeo, [], {#isMetric: isMetric}),
                  ),
                ),
          )
          as _i10.Future<_i3.Either<_i11.Failure, _i12.MeteoEntity>>);

  @override
  _i10.Future<bool> getPermission() =>
      (super.noSuchMethod(
            Invocation.method(#getPermission, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<void> saveToCache(_i12.MeteoEntity? data) =>
      (super.noSuchMethod(
            Invocation.method(#saveToCache, [data]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [FavoritesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesUseCase extends _i1.Mock implements _i17.FavoritesUseCase {
  MockFavoritesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<bool> checkFavoriteOrNo(String? cityName) =>
      (super.noSuchMethod(
            Invocation.method(#checkFavoriteOrNo, [cityName]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<void> addCityToFavorites(String? cityName) =>
      (super.noSuchMethod(
            Invocation.method(#addCityToFavorites, [cityName]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> deleteFromFavorites(String? cityName) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFromFavorites, [cityName]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<String>> getFavoritesList() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoritesList, []),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
          )
          as _i10.Future<List<String>>);
}

/// A class which mocks [MeteoEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeteoEntity extends _i1.Mock implements _i12.MeteoEntity {
  MockMeteoEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get cityName =>
      (super.noSuchMethod(
            Invocation.getter(#cityName),
            returnValue: _i18.dummyValue<String>(
              this,
              Invocation.getter(#cityName),
            ),
          )
          as String);

  @override
  _i7.LocationInfo get location =>
      (super.noSuchMethod(
            Invocation.getter(#location),
            returnValue: _FakeLocationInfo_5(
              this,
              Invocation.getter(#location),
            ),
          )
          as _i7.LocationInfo);

  @override
  _i8.CurrentWeather get current =>
      (super.noSuchMethod(
            Invocation.getter(#current),
            returnValue: _FakeCurrentWeather_6(
              this,
              Invocation.getter(#current),
            ),
          )
          as _i8.CurrentWeather);

  @override
  List<_i19.HourlyWeather> get hourlyForecast =>
      (super.noSuchMethod(
            Invocation.getter(#hourlyForecast),
            returnValue: <_i19.HourlyWeather>[],
          )
          as List<_i19.HourlyWeather>);

  @override
  List<_i20.DailyWeather> get dailyForecast =>
      (super.noSuchMethod(
            Invocation.getter(#dailyForecast),
            returnValue: <_i20.DailyWeather>[],
          )
          as List<_i20.DailyWeather>);
}
