// Mocks generated by Mockito 5.4.6 from annotations
// in forecast_app_pet_proj/test/data/mappers/weather_mapper_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:forecast_app_pet_proj/domain/entities/meteo_enity/current_weather.dart'
    as _i3;
import 'package:forecast_app_pet_proj/domain/entities/meteo_enity/daily_weather.dart'
    as _i7;
import 'package:forecast_app_pet_proj/domain/entities/meteo_enity/hourly_weather.dart'
    as _i6;
import 'package:forecast_app_pet_proj/domain/entities/meteo_enity/location_info.dart'
    as _i2;
import 'package:forecast_app_pet_proj/domain/entities/meteo_enity/meteo_enity.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLocationInfo_0 extends _i1.SmartFake implements _i2.LocationInfo {
  _FakeLocationInfo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCurrentWeather_1 extends _i1.SmartFake
    implements _i3.CurrentWeather {
  _FakeCurrentWeather_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MeteoEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeteoEntity extends _i1.Mock implements _i4.MeteoEntity {
  MockMeteoEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get cityName =>
      (super.noSuchMethod(
            Invocation.getter(#cityName),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#cityName),
            ),
          )
          as String);

  @override
  _i2.LocationInfo get location =>
      (super.noSuchMethod(
            Invocation.getter(#location),
            returnValue: _FakeLocationInfo_0(
              this,
              Invocation.getter(#location),
            ),
          )
          as _i2.LocationInfo);

  @override
  _i3.CurrentWeather get current =>
      (super.noSuchMethod(
            Invocation.getter(#current),
            returnValue: _FakeCurrentWeather_1(
              this,
              Invocation.getter(#current),
            ),
          )
          as _i3.CurrentWeather);

  @override
  List<_i6.HourlyWeather> get hourlyForecast =>
      (super.noSuchMethod(
            Invocation.getter(#hourlyForecast),
            returnValue: <_i6.HourlyWeather>[],
          )
          as List<_i6.HourlyWeather>);

  @override
  List<_i7.DailyWeather> get dailyForecast =>
      (super.noSuchMethod(
            Invocation.getter(#dailyForecast),
            returnValue: <_i7.DailyWeather>[],
          )
          as List<_i7.DailyWeather>);
}
