// Mocks generated by Mockito 5.4.6 from annotations
// in forecast_app_pet_proj/test/presentation/state_management/cubit/favorite_cubit/favorite_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:forecast_app_pet_proj/data/repositories_data_impl/data_remote_repo.dart'
    as _i3;
import 'package:forecast_app_pet_proj/domain/entities/meteo_enity/meteo_enity.dart'
    as _i6;
import 'package:forecast_app_pet_proj/domain/failures/failure_interface.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DataRemoteRepoIMPL].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataRemoteRepoIMPL extends _i1.Mock
    implements _i3.DataRemoteRepoIMPL {
  MockDataRemoteRepoIMPL() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MeteoEntity>> getRespByName({
    required bool? isMetric,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRespByName, [], {
              #isMetric: isMetric,
              #name: name,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.MeteoEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.MeteoEntity>(
                    this,
                    Invocation.method(#getRespByName, [], {
                      #isMetric: isMetric,
                      #name: name,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.MeteoEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MeteoEntity>> getRespByGeo({
    required bool? isMetric,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRespByGeo, [], {#isMetric: isMetric}),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.MeteoEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.MeteoEntity>(
                    this,
                    Invocation.method(#getRespByGeo, [], {#isMetric: isMetric}),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.MeteoEntity>>);

  @override
  _i4.Future<bool> getPermission() =>
      (super.noSuchMethod(
            Invocation.method(#getPermission, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> saveToCache(_i6.MeteoEntity? data) =>
      (super.noSuchMethod(
            Invocation.method(#saveToCache, [data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
