// Mocks generated by Mockito 5.4.6 from annotations
// in forecast_app_pet_proj/test/presentation/state_management/cubit/network_check_cub/network_cubi_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:forecast_app_pet_proj/core/services/network_checker/network_checker_serv.dart'
    as _i3;
import 'package:internet_connection_checker/internet_connection_checker.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeInternetConnectionChecker_0 extends _i1.SmartFake
    implements _i2.InternetConnectionChecker {
  _FakeInternetConnectionChecker_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NetworkCheckerServ].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkCheckerServ extends _i1.Mock
    implements _i3.NetworkCheckerServ {
  MockNetworkCheckerServ() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.InternetConnectionChecker get serv =>
      (super.noSuchMethod(
            Invocation.getter(#serv),
            returnValue: _FakeInternetConnectionChecker_0(
              this,
              Invocation.getter(#serv),
            ),
          )
          as _i2.InternetConnectionChecker);

  @override
  _i4.Future<bool> checking() =>
      (super.noSuchMethod(
            Invocation.method(#checking, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
